### PR TITLE
fix(core): fix subject-condition-sets Create/Update with protojson marshaling

### LINKED ISSUE #244: SCS update appears to succeed but subsequent get is unexpectedly missing values
Update command of SCS that exists already under that ID:
```shell
otdfctl policy subject-condition-sets update --id=fc3a7754-e7ab-438b-9081-558cf8ae5a0a -s '[{"condition_groups":[{"boolean_operator":2,"conditions":[{"subject_external_selector_value":".attributes.something[]","operator":1,"subject_external_values":["a","b","c","d"]},{"subjectExternalSelectorValue":".email","operator":3,"subjectExternalValues":["test.com","test.biz"]}]}]}]'

  SUCCESS   Updated subject-condition-sets: fc3a7754-e7ab-438b-9081-558cf8ae5a0a                                                                                                                                                                      
                                                                                                                                                                                                                                                      
╭─────────────────────────────────────┬─────────────────────────────────────╮                                                                                                                                                                         
│Property                             │Value                                │                                                                                                                                                                         
├─────────────────────────────────────┼─────────────────────────────────────┤                                                                                                                                                                         
│Id                                   │fc3a7754-e7ab-438b-9081-558cf8ae5a0a │                                                                                                                                                                         
│SubjectSets                          │[{"condition_groups":[{"conditions":…│                                                                                                                                                                         
│Created At                           │Thu Jul 18 19:03:06 UTC 2024         │                                                                                                                                                                         
│Updated At                           │Thu Aug  1 21:04:00 UTC 2024         │                                                                                                                                                                         
╰─────────────────────────────────────┴─────────────────────────────────────╯    
```

Subsequent GET fails to populate the fields and values when the operator is `IN_CONTAINS` / enum index 3:
```shell
otdfctl policy subject-condition-sets get --id=fc3a7754-e7ab-438b-9081-558cf8ae5a0a --json 
{
  "id": "fc3a7754-e7ab-438b-9081-558cf8ae5a0a",
  "subject_sets": [
    {
      "condition_groups": [
        {
          "conditions": [
            {
              "subject_external_selector_value": ".attributes.something[]",
              "operator": 1,
              "subject_external_values": [
                "a",
                "b",
                "c",
                "d"
              ]
            },
            {
              "operator": 3
            }
          ],
          "boolean_operator": 2
        }
      ]
    }
  ],
  "metadata": {
    "created_at": {
      "seconds": 1721329386,
      "nanos": 788121000
    },
    "updated_at": {
      "seconds": 1722546240,
      "nanos": 565223000
    }
  }
}
```

Note: this may be on the platform side?

### PR DESCRIPTION
**Pull request by jakedoublev**
Resolves #244 

Utilizes protojson and json.RawMessage for arrays of protos to properly marshal/unmarshal protos as json. The prior implementation seemingly ignored fields at times and this is the approach taken by the platform and recommended for proto marshaling.

### CODE REVIEW

File: cmd/policy-subjectConditionSets.go [hunk 1]
```diff
@@ -41,7 +73,7 @@ func policy_createSubjectConditionSet(cmd *cobra.Command, args []string) {
 		}
 		defer jsonFile.Close()
 
-		bytes, err := ioutil.ReadAll(jsonFile)
```
Comment (jakedoublev) [inline cmd/policy-subjectConditionSets.go:44]: This was marked deprecated and replaced with `io.ReadAll`.

**Review by jrschumacher — APPROVED** [review]
