### PR TITLE
fix(core): GOOS, error message fixes

### LINKED ISSUE #376: GOOS profiles tech debt cleanup
All of the following are tested:

| built on | runtime GOOS | `profiles` visible | client creds / host (no profile) | works |
| ---------- | ------------ | ------------------ | -------------------------------- | - |
| darwin     | darwin       | ✅                 | ✅                               | [ ] |
| darwin     | linux        | ❌                 | ✅                               | [ ] |
| linux      | linux        | ❌                 | ✅                               | [ ] |
| linux      | darwin       | ✅                 | ✅                               | [ ] |

### LINKED ISSUE #377: Required/optional ID flags should report better error messages
1. The CLI should have intelligence to try to parse flag values that are expected to be UUIDs
2. The CLI should report better error messages contextualizing received/expected values when flags expect UUIDs but received non-UUID strings
3. BATS test

This error below was on `attribute screate` when `--namespace-id` was a namespace name and not an ID, and has caused confusion for users.

```shell
  ERROR    Failed to create attribute: rpc error: code = InvalidArgument desc = invalid input syntax for type uuid
  ```

### LINKED ISSUE #380: Misleading error message when platform cannot be reached
If the CLI is utilized in any manner with the `--host` platform endpoint or saved profile platform endpoint not reachable (incorrect host or platform not running), the CLI reports an error `"Profile missing credentials. Please login or add client credentials."`

This is misleading.

Error messages should be provided for these separate cases (with e2e tests):
1. could not get platform config at provided host
2. client credentials were invalid
3. client credentials were not parse-able JSON
4. host provided but not client creds
5. client creds provided but not host

### PR DESCRIPTION
**Pull request by jakedoublev**
Resolves #377 
Resolves #376 
Resolves #380

### CODE REVIEW

**Comment by jakedoublev** [comment]
| built on | runtime GOOS | `profiles` visible | client creds / host (no profile) | works |
| ---------- | ------------ | ------------------ | -------------------------------- | - |
| darwin     | darwin       | ✅                 | ✅                               | ✅ |
| darwin     | linux        | ❌                 | ✅                               | ✅  |
| linux      | linux        | ❌                 | ✅                               | ✅ |
| linux      | darwin       | ✅                 | ✅                               | ✅  |

File: cmd/profile.go [hunk 1]
```diff
@@ -10,9 +10,15 @@ import (
...
+	runningInLinux         = runtime.GOOS == "linux"
+	runningInLinuxTestMode = runningInLinux && config.TestMode == "true"
+)
+
 var profileCmd = &cobra.Command{
-	Use:   "profile",
-	Short: "Manage profiles (experimental)",
+	Use:    "profile",
+	Short:  "Manage profiles (experimental)",
+	Hidden: runningInLinux && !runningInLinuxTestMode,
```
Comment (jrschumacher) [inline cmd/profile.go:21]: nit: considering `(A and not(A and B))` to resolve `not(A and B)` a must be true so this would be `(A and not(true and B))` which is the same as `(A and not(B))`

File: e2e/kas-grants.bats [hunk 2]
```diff
@@ -235,4 +235,22 @@ teardown_file() {
...
+}
+
+@test "optional ID flag string error message" {
+    export NS_ID_FLAG='--namespace-id hello'
+    export ATTR_ID_FLAG='--attribute-id world'
+    export VAL_ID_FLAG='--value-id goodnight'
+
+    run_otdfctl_kasg unassign $NS_ID_FLAG $KAS_ID_FLAG
+      assert_failure
+      assert_output --partial "Optional flag '--namespace-id' received value 'hello' and must be a valid UUID if used"
```
Comment (jrschumacher) [inline e2e/kas-grants.bats:247]: At some future point we should have some utility that exports all our error strings into a bats file so we can make these assert_output more durable.

**Review by jrschumacher — APPROVED** [review]

**Review by jrschumacher — APPROVED** [review]
